### ISSUE TITLE
Not clear about  .pipeline(obj, [callback])

### ISSUE THREAD

**Issue by RajPratim21** [cshum/levi#23]
Heu @cshum  I am not clear about .pipeline(obj, [callback]) explained here https://www.npmjs.com/package/levi#pipelineobj-callback.
does it do some kind of tokenization as provided in the example , i.e. placeholder -> placehold? these kinds of stuffs?

**Comment by cshum** [comment]
yes if `levi.stemmer()` "middleware" applied i.e.
```js
var lv = levi('db') 
.use(levi.tokenizer())
.use(levi.stemmer())
.use(levi.stopword())
```
